[project]
name = "advanced-ml-02460"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "numpy>=2.4.2",
    "scipy>=1.17.1",
    "torch>=2.10.0",
]
